### ISSUE TITLE
more generalization rules for features of the Adult dataset

### ISSUE THREAD

**Issue by RunshanHu** [leo-mazz/crowds#2]
Hi,

Is there more generalization rules available for features of the Adult dataset?

thanks

**Comment by leo-mazz** [comment]
Hi,
The current generalization rules available are just a stump! However, creating new rules is really very easy. Do let me know if you encounter a problem doing that, and please feel free to contribute to the project. Development has currently slowed down, and priority is implementing more algorithms rather than generalization rules, which should mostly be user-defined.

Thanks.
